Jpeg mode
adafruit/Adafruit_CircuitPython_OV2640 pull request #4
Opened 2021-07-14 16:08 UTC by jepler

.. including an example for Kaluga which captures to the internal CIRCUITPY flash region.

2021-07-14 16:11 UTC, jepler commented
@ladyada do you want to test this yourself? do you want an example that uses SD card instead of CIRCUITPY? (shouldn't be too difficult, just would need to wire it up)

2021-07-14 17:09 UTC, ladyada commented
i dont need to test it - thankx! please check the OV2640 datasheet, anything else interesting in there? filters?

2021-07-14 17:43 UTC, tannewt requested changes
Two minor things you might want to do. I'm ok if you don't want to do them.

2021-07-14 17:43 UTC, tannewt commented on adafruit_ov2640.py
> +    [
If you want to save import memory then you could switch this to an ugly bytes literal. As-is it's a list construction that is then converted to bytes.

2021-07-14 17:43 UTC, tannewt commented on adafruit_ov2640.py
> +        if colorspace == OV2640_COLOR_RGB:
Want to use a dictionary to lookup the corresponding settings?

2021-07-15 14:56 UTC, jepler commented on adafruit_ov2640.py
> +        if colorspace == OV2640_COLOR_RGB:
done!

2021-07-15 14:57 UTC, jepler commented
@tannewt ready for a re-review.  I added a 2nd jpeg demo which turns the Kaluga into a selfie-cam.  Press (hold, really, because it's polled) the REC button to save a jpeg image at highest resolution to an SD card.

![img0003](https://user-images.githubusercontent.com/1517291/125809803-1cfe130f-d66e-46b6-b965-fac7ab060b26.jpg)

2021-07-15 23:28 UTC, tannewt approved these changes
Looks great! Thank you!

2021-07-15 23:29 UTC, merged

2021-07-17 21:31 UTC, ladyada commented
nice work!